version: '3'
services:
  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"

  bff-service-rest:
    container_name: rest-api
    image: bff-service-rest:latest
    ports:
      - "8080:8080"
    environment:
      - spring.application.name=bff-service-rest
      - info.app.environment=dev
      - spring.datasource.url=jdbc:mysql://mysql:3306/masters_v1?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=password
      - spring.jpa.hibernate.ddl-auto=update
    depends_on:
      - db

  angular-app:
    container_name: angular-ui
    build:
      context: ./angular-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./angular-ui/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bff-service-rest
