name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: mire323
password: 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
- name: Build the hello-docker Docker image
run: |
       docker build . --tag masters.io/mirko-bff-service:latest
       docker run masters.io/mirko-bff-service:latest
       docker push gmasters.io/mirko-bff-service:latest